# Problem

In [1]:
import numpy as np
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a)) # overflow

/home/jingsheng/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/home/jingsheng/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan, nan, nan])

# Improvement

In [2]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [3]:
np.exp(a-c) / np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])